### ISSUE TITLE
Redesign the page!

### ISSUE THREAD

**Issue by vspedr** [vspedr/developets#11]
Feel free to modify the page as much as you want, such as using different colors or changing the ui framework from semantic-ui to something else :smile:

**Comment by igorrmon** [comment]
Hello, I am interested in contributing to this issue, are you getting PR's?

**Comment by vspedr** [comment]
Sure!

**Comment by vspedr** [comment]
Hi @igoRmon are you still working on this? I'm going to create smaller design related issues to make it easier for people to contribute. If you have already worked on it you can still create a PR, it will count towards Hacktoberfest even if I don't merge it
