### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by vspedr** [vspedr/developets#17]
As the list increases, loading too many items at once may cause some performance issues. We could use pagination to limit the amount of items displayed.

**Comment by fuku710** [comment]
I want to do this issue!

**Comment by vspedr** [comment]
Hi @fuku710, feel free to give it a try!

**Comment by vspedr** [comment]
Hey @fuku710 just a heads up, if you're working on this take a look at #20, I will merge it soon so pagination should probably take it into account

**Comment by fuku710** [comment]
@vspedr OK

**Comment by Iodine-** [comment]
Happy to assist with this too if needed @fuku710 - just let me know if there is anything I can do

**Comment by fuku710** [comment]
Thank you @Iodine- !
I will write code hard but if you know better code to tell me

**Comment by akankshajai** [comment]
Is this still open? I want to work on this.

**Comment by vspedr** [comment]
Hi @akankshajai, sorry, this is already implemented but I forgot to close the issue. Feel free to browse the issues and pick another one!

**Comment by vspedr** [comment]
Implemented in #22

**Comment by akankshajai** [comment]
Hi Vspedr/Developets,

Thank you for your response.

Regards,
Akanksha
