### ISSUE TITLE
Make the card pictures square

### ISSUE THREAD

**Issue by vspedr** [vspedr/developets#23]
The cards would look much better if the image on them was cropped into a square (equal width and height) while maintaining the aspect ratio of the original image. Size should be something such as 240x240 for mobile devices and 320x320 for the rest

**Comment by humanolaranja** [comment]
I'd like to do this one =D

**Comment by humanolaranja** [comment]
Aguardando merge, pull request #27

**Comment by vspedr** [comment]
Fixed in #27
