### ISSUE TITLE
Create placeholder to show if data fails to load

### ISSUE THREAD

**Issue by vspedr** [vspedr/developets#31]
If for some reason the pet list fails to load, the page should display a friendly message. Use your creatiity :)

**Comment by abhnv42** [comment]
May I  work on this ?

**Comment by vspedr** [comment]
Sure @abhnvgupta!

**Comment by sprakash57** [comment]
Is this still open?

**Comment by vspedr** [comment]
@abhnvgupta are you still working on this issue?

**Comment by abhnv42** [comment]
Yes... It'll take me few more hours to do this... I'm new to React...

**Comment by vspedr** [comment]
No problem @abhnbgupta, take your time!

@sprakash57 this issue is taken, but feel free to send a PR with any other improvements you can think of
