### ISSUE TITLE
Use local storage to cache requests

### ISSUE THREAD

**Issue by vspedr** [vspedr/developets#37]
We are using axios to fetch pets data from an external source and we have pagination set up so that every page loaded triggers a new request. This could be improved with something like [this](https://github.com/RasCarlito/axios-cache-adapter#use-localforage-as-cache-store) so that we first check if data is stored locally before actually sending a request to the server.

Bonus challenge: implement pre-fetching so that, for example, when I navigate to page 2, page 3 is loaded in advance, then when I navigate to page 3, page 4 is loaded in advance and so on. Can be a separate PR.

**Comment by camdunne** [comment]
Hi @vspedr, I would like to take this on and submit a PR. Thanks!

**Comment by vspedr** [comment]
Done in #40
